version: 2
jobs:
  hello:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: 
          name: HELLO
          command: echo "A first hello" && export STH=$(printenv)
  hello2:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run: echo "hello2" $STH
     
workflows:
  version: 2
  HELLO:
   jobs:
     - hello:
         filters:
           branches:
             only: /.*/
     - approve:
         type: approval
         requires: 
           - hello
     - hello2:
         requires:
           - approve
