version: 2
jobs:
  hello:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: 
          name: HELLO
          command: echo "A first hello"
  hello2:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
     run: echo "hello2"
     
workflows:
  version: 2
  HELLO:
   jobs:
     - hello:
         filters:
           branches:
             only: /.*/
     - approve:
         type: approval
         requires: 
           - hello
     - hello2:
        requires:
          - approve
