version: 2
jobs:
  hello:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: mkdir ws
      - run: 
          name: HELLO
          command: echo "A first hello" && export STH=$(printenv) && echo $STH > ./ws/sth
      - persist_to_workspace:
          root: ws
          paths:
            - sth
  hello2:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - attach_workspace:
          at: ./
      - run: echo "hello2" $STH
      - run: ls -la
      - run: cat ws/sth
     
workflows:
  version: 2
  HELLO:
   jobs:
     - hello:
         filters:
           branches:
             only: /.*/
     - approve:
         type: approval
         requires: 
           - hello
     - hello2:
         requires:
           - approve
